### ISSUE TITLE
Range/Scoring/STAR Voting: simplified format (fixed order of candidates, separated by comma)

### ISSUE THREAD

**Issue by masiarek** [electorama/abif#19]
New format requested.

Instead of this:
=DGM:[Doña García Márquez]
=SBJ:[Steven B. Jensen]
=SY:[Sue Ye (蘇業)]
=AM:[Adam Muñoz]

27: DGM/5, SBJ/2, SY/1, AM/0
26: DGM/3, SBJ/5, SY/3, AM/1
24: DGM/2, SBJ/1, SY/5, AM/2
23: DGM/1, SBJ/0, SY/3, AM/5

use double equals sign (maybe instead of two equals - we should use tilde character ~:
==DGM:[Doña García Márquez]
==SBJ:[Steven B. Jensen]
==SY:[Sue Ye (蘇業)]
==AM:[Adam Muñoz]

27: 5, 2, 1, 0
26: 3, 5, 3, 1
24: 2, 1, 5, 2
23: 1, 0, 3, 5

Idea: double equal sign (or alternative character - say: ~ ) indicates scoring ballot, with fixed order and columns are required.
This is OK:
23: 1, 0, 3, 5
and this is OK
23: 1, , 3, 5

However, this is not OK - should fail with error:
23: 1, 3, 5
Error:  number of candidates (4) and number of scores (3) must match.

However, this is not OK - should fail with error:
23: 1, 0, 3, 5, 4
Error:  number of candidates (4) and number of scores (5) must match.

**Comment by robla** [comment]
Here's my rationale for a single equals sign.  I believe that ALL implementations should implement parsing for [UTF-7](https://en.wikipedia.org/wiki/UTF-7) "lines", where two "lines" full the letters `ABC` should look like this.

```
ABCABCABC
ABCABCABC
```

...and the beginning of each line should start with an easily-parsed UTF-7 character.  Most modern programming languages have good support for UTF-8, and thus it's possible for those two lines to start with the following:

```
ABCABCABC
ABCABCABC
```

What I'm realizing now (looking at the [UTF-7 Wikipedia page](https://en.wikipedia.org/wiki/UTF-7)) is that equals-sign ("`=`") at the beginning of a line might be tough in some contexts.  It seems that tilde ("`~`") is likely to be even worse.

I'm not sure I understand the example you posted, @masiarek , but I wouldn't be surprised if it's a cut-n-paste of an example out of the test suite.  The example I'm referring to is this one (for which I'll put a comment line on the top)

```
# masiarek's initial example with double-equals in issue #19
==DGM:[Doña García Márquez]
==SBJ:[Steven B. Jensen]
==SY:[Sue Ye (蘇業)]
==AM:[Adam Muñoz]

27: 5, 2, 1, 0
26: 3, 5, 3, 1
24: 2, 1, 5, 2
23: 1, 0, 3, 5
```

My implementation (when I write it) would treat that file as equivalent to this file

```
# robla's "November scramble" of masiarek's example from issue #19
==AM:[Adam Muñoz]
==DGM:[Doña García Márquez]
==SBJ:[Steven B. Jensen]
==SY:[Sue Ye (蘇業)]

27: 5, 2, 1, 0
26: 3, 5, 3, 1
23: 1, 0, 3, 5
24: 2, 1, 5, 2
```

A ranked-method implementation would have a very difficult time parsing the examples above because it's not clear what the numbers are mapped to.  The `==` lines are intended to provide simple UTF-7 characters for complicated UTF-8 labels, but the order of those mappings should not matter.  Are you implicitly making the case for line ordering mattering?

**Comment by masiarek** [comment]
I am looking for an indicator to trigger a new file format - e.g. Score Voting - but a) WITHOUT nasty slash characters and b) more terse file format (fixed number of columns and providing scores only - without repeating candidates ).
Here are some scenarios I created for STAR Voting - please let me know how to improve the format (I like the idea of using the same ballot data for both Ranking and Scoring methods - but without using SLASH character): 
https://github.com/masiarek/STAR_Voting/tree/main/FileFormat/PositiveFileFormatTestCases 

Your Test Scenario 'Case 3 - Scores using = and > as delimiters'
- using a Slash character to assign scores - this looks pretty ugly. There must be a better way!
- using '>' as a delimiter? Why not a simple comma? I would assume that we should keep < and > characters for Rankings.

Case 10 - Declared, bracketed candidate tokens.  Unordered scores.
- How to avoid repeating the candidates? In a scored method - columns can be pretty much fixed (blank values can be represented as serious of commas: ,,,  or   zeros:  ,0,0,0)

Anyhow it is getting late. I will try to explain better next time. THANK YOU!

**Comment by robla** [comment]
Hi @masiarek  -- thanks for explaining how you thought ranks were expressed.

> Do I understand the intention of an 'interoperable (score vs ranking) formatting' correctly?

I'm worried that you do not.  Many online systems that support ranked voting support input files that look like this:

```
42:Mem>Nas>Cha>Kno
26:Nas>Cha>Kno>Mem
15:Cha>Kno>Nas>Mem 
17:Kno>Cha>Nas>Mem
```

"`Mem`", "`Nas`","`Cha`" and "`Kno`" are all implicitly candidate tokens, and don't need to be declared as tokens.  It's these kind of files that I'm hoping to maintain backwards compatibility with, because many people in online debates still use a very similar format.  The order of the ranking is inferred from the left-to-right order of the characters on the line.  A number for the ranking doesn't need to be specified.

The two tokens that matter for inferring the ranking are "`>`" and "`=`".  The leftmost candidate is at the top of the list, and then candidates can be tiered.  So, let's say the 26 voters that favor "`Nas`" above all others are indifferent about the choice between "`Cha`" and "`Kno`", rather than explicitly favoring "`Cha`" over "`Kno`".  That would be expressed this way:

```
26:Nas>Cha=Kno>Mem
```
Comma ("`,`") is an _optional_ delimiter for systems that only accept ratings (rather than rankings).  In cases where comma is used, perhaps a rating should be required.

The reasons for requiring ratings-based systems to repeat the candidates on each line are manifold.  The biggest reason is because there would be no other way to infer the candidates from the line in isolation of other lines.

Regarding the beginning character in the line for candidate declarations: you have given me an idea that plays off of my idea in issue #9.  What if we made it so that up to four equals signs (`====`) is the preferred token for the beginning of a line that has a candidate token.  My first "`Mem`"/"`Nas`"/"`Cha`"/"`Kno`" example above could equivalently be expressed this way:

```
====M:[Mem]
====N:[Nas]
====C:[Cha]
====K:[Kno]
42:M>N>C>K
26:N>C>K>M
15:C>K>N>M 
17:K>C>N>M
```

Less forgiving implementations could _require_ a full four equals signs and square brackets around the UTF-8 string.  But forgiving implementations could also accept this:

```
=M:Mem
=N:Nas
=C:Cha
=K:Kno
42:M>N>C>K
26:N>C>K>M
15:C>K>N>M 
17:K>C>N>M
```

Issue #19 (this issue) has many subissues, and I would prefer to have exactly one question per issue.  We can either turn issue #19 into an issue focused on one of these issues, or close this issue and file all of the subissues as new issue here in Github.  The list:

a. Should the candidate order be the same for every line of an ABIF file, with rankings expressed numerically?
b. Should the rating of a candidate token and the candidate rating be separated using a forward slash ("`/`") or some other character?
c. What should be the first character (or sequence of characters) on lines that map lower-ASCII candidate tokens to full UTF-8 candidate strings?  ("`=`", "`==`", "`====`", or something else?)

**Comment by masiarek** [comment]
hi Rob, you are right - it is better to close this topic as a 'non-issue'. 
I got sidetracked by Ranking method format - but I am working on STAR Voting method (Scoring method). 

Here is a draft document with some test scenarios:  https://docs.google.com/spreadsheets/d/1BjRCM5Us6TWfRheXE2Zspp8ce2LKPMhzjcuJ4HPI3TY/edit#gid=0 

Please note that we use a separate file - Election Parameters - to define expectations from the file format.
Election Parameters file is using parameters - here are some examples:
a) Voting Method Type (e.g. STAR Voting)
b) Single or Multi-winner Election
c) Number of Seats
d) Delimiter Type (comma, space, tab, mixed)
e) Weighted Voting Allowed
f) Expected Upload File Format (including ABIF)
g) Implied Candidate Names (no need for Candidate names - assume standard A, B, C, etc.).

I will continue updating Functional Specification doc at: https://docs.google.com/document/d/1x9lwhHUYAGa1JVrKuqQ1WKHYoXUEtvySH8KC3YY1ARY/edit#heading=h.ufj0s345hyta

Once done - we can re-visit and see what can be improved or are there any options  / potentials for synergy.
