### ISSUE TITLE
Decide what the letter "I" in "ABIF" stands for, or if "ABIF" is the correct acronym

### ISSUE THREAD

**Issue by robla** [electorama/abif#2]
In June 2021, Neal McBurnett suggested that "image" shouldn't be part of the name (see "[[EM] Re: Ballot Data Format](http://lists.electorama.com/pipermail/election-methods-electorama.com/2021-June/002794.html)").  Since many places use "ballot image" to refer to the ASCII representation of ballots, I'm not sure I want to try to change the standard naming by the election machine industry, but I agree that when I think of "image" formats, I usually think of JPEG, GIF, PNG, and other image formats that are common on the web.  Moreover, I like the name "ABIF", and don't want to change it at this point.

So the question: which of the following should the format be named?
a. Aggregated Ballot Image Format
b. Aggregated Ballot Information Format
c. Aggregated Ballot Inventory Format
d. Something else that still spells "ABIF" as an acronym
e. Something else that doesn't spell "ABIF" as an acronym

**Comment by simberaj** [comment]
IMHO variants b and c are preferable to mitigate confusion with actual ballot images. My personal favorite is b.

**Comment by brainbuz** [comment]
If the spec for a writer will be to aggregate identical ballots and Ballot Image image may imply one ballot per line, Aggregate Ballot Information Format is more accurate, and less ambiguous to someone unfamiliar of the usage of Image in this context.

**Comment by nealmcb** [comment]
Thanks, Rob. Though at any reference to "ASCII" in a standards discussion, I feel obligated to note that of course no format which represents people's names should ever again use ASCII instead of e.g. UTF-8. I don't see the character encoding to use specified at ElectoWiki, so I'll suggest here that it really must be specifed, as UTF-8

On the present issue, I agree with simberaj, and like the very cogent point by brainbuz that aggregation is incongruent with images.

To flesh that out a bit, as I noted in the referenced email, the latest [Voluntary Voting System Guidelines 2.0](https://www.eac.gov/sites/default/files/TestingCertification/Voluntary_Voting_System_Guidelines_Version_2_0.pdf) clearly define ballot images in the normal sense of the word: 

> ballot image: Archival digital image (e.g. JPEG, PDF, etc.) captured from one or more sides of a paper ballot cast by an individual voter.

The generic technical term for the records we're trying to define is "Cast Vote Records" (CVR). Even though I rarely hear people call CVRs ballot images any more, we still had to work hard to get the definition fixed in the VVSG, and it would be a real shame to lose ground with the latest CVR format.

But ABIF itself is fine to keep. I'd favor option `b`.

**Comment by robla** [comment]
Thanks everyone!  For the primary issue, we should all start referring to it as "Aggregated Ballot **Information** Format", and keep using "ABIF" as the acronym. I'll update any places where I still refer to ABIF as an "image format", changing it to an "information format".

Regarding @nealmcb 's comment about ASCII vs UTF-8:  yes, agreed, it should be UTF-8.  I'll try to be more careful about how I refer to it.  I cover this in much more depth in newly-filed issue #5 .  I'll update [the ABIF page on electowiki](https://electowiki.org/wiki/ABIF) momentarily.
