### ISSUE TITLE
Separate standards for ranked vs. scored ballots?

### ISSUE THREAD

**Issue by carlschroedl** [electorama/abif#7]
Scores and ranks are different. Should different standards exist for each?

**Comment by robla** [comment]
I'm excited about having a single format that supports scores and ranks. I see no reason to remove one or the other from ABIF.  Is there any of [the current testcases](https://github.com/electorama/abif/tree/main/testfiles) you would prefer to invalidate?

**Comment by brainbuz** [comment]
I think the file format should support all ballot types well. It will need to define multiple data types.
Ranked Ballots can be represented as Scored Ballots where the best score is low instead of high, which also immediately supports equal ranking.
One of the consensus goals is hand editing and these two formats for ranked ballots seem the most natural
A>B>C # Ranked
A=D>C>E=Y>F # Ranked permit equal
vs scored format:
A/1:B/2:C/3 
A/1:C/2:D/1:E/3:F/4:Y/3

**Comment by simberaj** [comment]
I am putting my effort into this precisely because it aims to represent all ballot types:

- Approval: `A, B, C` (simple plurality votes are a subset of this)
- Ranked: `A>B=C>D`
- Scored: `A/1, B/4, C/3, D/2`.

A single file should (RFC MUST) contain only one of these types of ballots, but otherwise, I think no additional markup should be added to specify which type is used.

**Comment by robla** [comment]
Consensus seems to be that ABIF should be able to handle both ranked and scored ballots, so I'm going to close this one out.
